// <auto-generated />
namespace badmintonDataBase.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class FalseAdd : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(FalseAdd));
        
        string IMigrationMetadata.Id
        {
            get { return "201705091725247_FalseAdd"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
