// <auto-generated />
namespace badmintonDataBase.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class PlaceInDrawAdd : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(PlaceInDrawAdd));
        
        string IMigrationMetadata.Id
        {
            get { return "201705080929506_PlaceInDrawAdd"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
